# This file was generated by GoReleaser. DO NOT EDIT.
cask "ws2tcp" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "0e504889d780e6221c38dcf2d044e6ba352ea14c2678a2c515fc5a939dac12fe"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
    on_arm do
      sha256 "05cf5b55a5431e17c65f87d157a2e8fdbc0f089e944f8e2734db56a1754b63e9"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
  end

  on_linux do
    on_intel do
      sha256 "86a04ef3fa3acd98452b02c810a9bf78eb517e23342ff539377b9aca1b39c03c"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_linux_amd64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
    on_arm do
      sha256 "584effb21c84f424082dcb9758d2c7c79559ec8e2550543b16eba9d8a4fc5f6c"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_linux_arm64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
  end

  name "ws2tcp"
  desc "WebSocket tunnel for transparent TCP forwarding with end-to-end encryption."
  homepage "https://github.com/HobaiRiku/ws2tcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ws2tcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ws2tcp"]
    end
  end

  # No zap stanza required

end
