# This file was generated by GoReleaser. DO NOT EDIT.
cask "ws2tcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "09566cf57314a8dd149183fa04aa852667765243efe438241ad1010b26147bf1"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
    on_arm do
      sha256 "d77368f6d69eb860d169be8352d7941fe49b6b2afadfd6cbea6e2e25b6443d89"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
  end

  on_linux do
    on_intel do
      sha256 "01e0af78eb9eeb32ce4a94b041cb9931a10f466c6628bc62cd7c8e3a4e2c9cff"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_linux_amd64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
    on_arm do
      sha256 "89a8618fee08900a0fdd72b024b5dd8099c61b42e3acc1489f2753a97f5d1de6"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_linux_arm64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
  end

  name "ws2tcp"
  desc "WebSocket tunnel for transparent TCP forwarding with end-to-end encryption."
  homepage "https://github.com/HobaiRiku/ws2tcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ws2tcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ws2tcp"]
    end
  end

  # No zap stanza required

end
