# This file was generated by GoReleaser. DO NOT EDIT.
cask "ws2tcp" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "244fb3e23bac50405b15f49481f92fb6e0d158dbf06e957175797265c810a10f"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
    on_arm do
      sha256 "983952f7c1ba28546e586030b7fb087baea88a4d72249280f4d9210bca176906"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a26d1687020c29eb480195a83328d589ccf6ad92fa2a84c6755d4ab055a70ba9"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_linux_amd64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
    on_arm do
      sha256 "6e8734087567f06d40c73d9eb9f5a307f0eef0efc0158999cf1701560b380e93"
      url "https://github.com/HobaiRiku/ws2tcp/releases/download/v#{version}/ws2tcp_#{version}_linux_arm64.tar.gz",
        verified: "github.com/HobaiRiku/ws2tcp/"
    end
  end

  name "ws2tcp"
  desc "WebSocket tunnel for transparent TCP forwarding with end-to-end encryption."
  homepage "https://github.com/HobaiRiku/ws2tcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ws2tcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ws2tcp"]
    end
  end

  # No zap stanza required

end
