# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hosta < Formula
  desc "Fast interactive SSH host launcher built on top of OpenSSH"
  homepage "https://github.com/HobaiRiku/hosta"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HobaiRiku/hosta/releases/download/v0.0.2/hosta_0.0.2_darwin_amd64.tar.gz"
      sha256 "c3c0dd7cb0a3b1b315a16c8f65e3b98b6de5f412c84fb12067367989798512fc"

      define_method(:install) do
        bin.install "hosta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HobaiRiku/hosta/releases/download/v0.0.2/hosta_0.0.2_darwin_arm64.tar.gz"
      sha256 "b258fdc0a25f1af419d6c773c0cd6635e3911ebdb33a7104604b819138bfce36"

      define_method(:install) do
        bin.install "hosta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/hosta/releases/download/v0.0.2/hosta_0.0.2_linux_amd64.tar.gz"
      sha256 "027b80c21d4c33c5043d9f876b4f3372ca8b6d26b9c424431032e92b2281002b"
      define_method(:install) do
        bin.install "hosta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/hosta/releases/download/v0.0.2/hosta_0.0.2_linux_arm64.tar.gz"
      sha256 "48c943657d5a80c2f829d209d920ef107602a67ac8e68c17510c373de161fc49"
      define_method(:install) do
        bin.install "hosta"
      end
    end
  end

  test do
    system "#{bin}/hosta", "version"
  end
end
