# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshTunnelService < Formula
  desc "Cross-platform SSH tunnel daemon with CLI, API, and embedded web UI"
  homepage "https://github.com/HobaiRiku/ssh-tunnel-service"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.7/ssh-tunnel-service_0.0.7_darwin_amd64.tar.gz"
      sha256 "d03eec05eb88e84518f2953be2608dc296c137b08b61bd69981b97392533d95f"

      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.7/ssh-tunnel-service_0.0.7_darwin_arm64.tar.gz"
      sha256 "90f1c8ecdeeb20d9f471a176258d8303a5970afc27efeb751c5ef2eda3ef1f3f"

      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.7/ssh-tunnel-service_0.0.7_linux_amd64.tar.gz"
      sha256 "e34315c3225fbfa56fde146ee7d1df556b151404acfff6b7482f79c0dc514d3d"
      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.7/ssh-tunnel-service_0.0.7_linux_armv7.tar.gz"
      sha256 "954165e477fd4a13338896093e3b542800e5796ca619a7991bc0fbabb0129508"
      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.7/ssh-tunnel-service_0.0.7_linux_arm64.tar.gz"
      sha256 "3f578e753a964822cb677e1e42bc1b980771267888dba872367f2caed5c28275"
      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
  end

  test do
    system "#{bin}/ssh-tunnel", "version"
  end
end
