# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshTunnelService < Formula
  desc "Cross-platform SSH tunnel daemon with CLI, API, and embedded web UI"
  homepage "https://github.com/HobaiRiku/ssh-tunnel-service"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.10/ssh-tunnel-service_0.0.10_darwin_amd64.tar.gz"
      sha256 "79d6c2bc76740e9083cf2e46fd9e9fbc1b27b726b4c389cfa63ea67e8a2335db"

      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.10/ssh-tunnel-service_0.0.10_darwin_arm64.tar.gz"
      sha256 "8a38d203ed038a5ef73c360ab343f4db10588949f0c8a76c3e3f2c81041357f1"

      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.10/ssh-tunnel-service_0.0.10_linux_amd64.tar.gz"
      sha256 "c75c20f0f83bb7f2a6d0394485eb10487d10b68834ceefef7fc150e43a72c524"
      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.10/ssh-tunnel-service_0.0.10_linux_armv7.tar.gz"
      sha256 "4987864794e01a851a6947639f20f3a13c402cef4cfc0687c348e909860b4c2f"
      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HobaiRiku/ssh-tunnel-service/releases/download/v0.0.10/ssh-tunnel-service_0.0.10_linux_arm64.tar.gz"
      sha256 "c551647bd780ce6abdb586824adb84c0ffe9b37084bc814b97b959c93fd2b9b0"
      define_method(:install) do
        bin.install "ssh-tunnel"
      end
    end
  end

  def caveats
    <<~EOS
      `ssh-tunnel install` copies the binary to a stable path and points the
      service unit at that copy, so upgrading this formula does not change what
      the running service executes. After an upgrade, run:

        ssh-tunnel update

      It refreshes the installed binary and restarts the service (auto-start
      tunnels reconnect on their own). `ssh-tunnel status` reports the version
      skew whenever the two drift apart.
    EOS
  end

  test do
    system "#{bin}/ssh-tunnel", "version"
  end
end
